# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0


FROM scratch

ARG SERVERLESS_ARCH=amd64

ADD .bin/processor-$SERVERLESS_ARCH /home/nuclio/bin/processor
